### ISSUE TITLE
[issue] Google Image Search

### ISSUE THREAD

**Issue by mzso** [meh/smart-referer#22] opened 2015-03-14 14:31 UTC
Hello!
A common issue I have is that images that show up or are opened from google image search are replaced by some sort of notification that hotlinking is not allowed.
eg: searching for "[random celebrity name]  fansshare" tends to bring.

I thought using this addon would help. But it doesn't or I don't know how to configure it...
On a related note. Websites allowed are getting the normal referrer or whatever this addon is set to send or vice versa?

**Comment by alexander255** [comment] 2015-03-15 15:23
1. I cannot reproduce your issue (but maybe I'm searching for the wrong things?). Could you open an affected preview image on the Google Image search and post it's address as a comment here?
2. This add-on only interferes with cross-domain (or cross-subdomain if in *Strict* mode) requests. This means that it will change the referer if a website `https://example.com/abc.html` loads the resource `https://yourdomain.net/cat.png` but not when loading `https://example.com/heading.gif`. The *Allow* rules allow you to specify rules such as `example.com>yourdomain.net` to prevent referer rewriting for these domains.

Your issue might not be related to this add-on: Try resetting the preferences `network.http.referer.XOriginPolicy`, `network.http.referer.spoofSource`, `network.http.referer.trimmingPolicy` and `network.http.sendRefererHeader` by going to `about:config`, acknowledging that you will be careful, searching for each of these, right-clicking each of them and selecting *Reset*.

**Comment by mzso** [comment] 2015-03-16 00:40
[This search](https://www.google.com/search?safe=off&tbm=isch&tbs=imgo:1&q=taylor%20swift%20fansshare#imgdii=_&imgrc=3pfEt-qtsYdACM%253A%3BDcyhaeooruPpbM%3Bhttp%253A%252F%252Fgerman.fansshare.com%252Fphotos%252Ftaylorswift%252Ftaylor-swift-grammy-awards-red-carpet-photos-red-carpet-769338587.jpg%3Bhttp%253A%252F%252Fpz-c-us.blogspot.com%252F2013%252F01%252Fred-taylor-swift-jan-01-2013-093710.html%3B860%3B1293) for example has a bunch of results like this:

[Here's one](http://img26.fansshare.com/cached/photos/taylorswift/taylor-swift-grammy-awards-red-carpet-photos-red-carpet-769338587.jpg) directly

> This add-on only interferes with cross-domain (or cross-subdomain if in Strict mode) requests. This means that it will change the referer if a website https://example.com/abc.html loads the resource https://yourdomain.net/cat.png but not when loading https://example.com/heading.gif.

I see. Well, I didn't come into a situation when I need the referrer changed on the same website.
But it would be nice if the referrer manipulation could be enabled for image urls. I think that might fix half of the issue.

**Comment by alexander255** [comment] 2015-03-28 23:32
I still can't seem to reproduce your issues with Google Image search, but here are a few observations/comments of mine:

 * Referer manipulation is enabled for everything when using **Smart Referer** - images are no exception
 * Google's search uses HTTPS/encryption while `fansshare.com` does not, this means that `fansshare.com` will never receive a referer when its images are being embeded into any Google website (HTTP resources loaded on HTTPS sites never receive a referer; this rule is hard-coded in most/all? browsers and can't be changed)
 * The example URL you have provided always produces the hotlinking warning, even if a correct referer is sent
 * When I click on the **View image** link next to any of fansshare's images I get redirected to the page where that image is used (an **img26.fansshare.com**-referer is sent in this case).

Conclusion:
 * All the issues seem to be related to how `fansshare.com` does things (with or without this extension)
 * I still can't reproduce your problem, as far as I can tell everything is working the way it should (and *Smart Referer* isn't disrupting anything)
 * What you are trying to do is outside of the scope of *Smart Referer*, maybe try [RefControl][https://addons.mozilla.org/de/firefox/addon/refcontrol/] instead? (I don't know if its maintained anymore, but if I remember correctly it can do what you want it do (per-page rules for faking referers)

Please let me know if I missed something, but I don't think that *Smart Referer* is the right tool for this job.

Sorry for not being able to be all that helpful!

**Comment by mzso** [comment] 2015-03-29 10:45
Thanks for the info!
> Google's search uses HTTPS/encryption while fansshare.com does not, this means that fansshare.com will never receive a referer when its images are being embeded into any Google website (HTTP resources loaded on HTTPS sites never receive a referer; this rule is hard-coded in most/all? browsers and can't be changed)
I see. So I guess this is the main issue. 

Also something changed. I can't reproduce it anymore and also google doesn't seem to load the full resolution picture like before. There was a sort of scrollbar like throbber thing under the image previews while while the full quality preview was loading.
(The old version of the "Mouseover Popup Image Viewer" userscript also fails to load images here now. Last time it was still working)
So somehow the problem fixed itself somehow.

**Comment by alexander255** [comment] 2015-03-29 12:11
Closing this issue then

**Closed by alexander255** 2015-03-29 12:11 UTC
