### ISSUE TITLE
Whitelist Atlassian ID

### ISSUE THREAD

**Issue by pera** [meh/smart-referer#106] opened 2018-09-06 01:23 UTC
Atlassian ID is needed for things like Jira, Confluence and Bitbucket. I currently use the following exception rule to be able to login: `id.atlassian.com>*`

Thanks!

**Comment by alexander255** [comment] 2018-09-06 17:50
Thank you for your feedback!
Since the list of Atlassian products is afaik quite finite, could you please provide a list of all the products that are affected by this? Also I just tried logging into that dusty old BitBucket account of mine and experienced no problems with the default whitelist (1st-party login with OTP), so could you provide some steps to reproduce on BitBucket for this problem so I can verify?

**Comment by pera** [comment] 2018-09-07 04:14
@alexander255 sure! yeah it would be nice to make that rule more strict but I couldn't figure out what domains exactly were required.
My issue was actually with Jira Cloud, but you are totally right about Bitbucket not being affected by this (sorry about my original post, I assumed all their services had the same issue because they all use Atlassian ID). You can reproduce this problem with a Jira free trial account: https://www.atlassian.com/software/jira/try

**Comment by alexander255** [comment] 2018-09-10 15:59
@pera: (Sorry for the delay.) Are the JIRA Cloud products hosted on a single domain (ie: `somename.atlassian.net`) or on each of their products domains (ie:`somename.bitbucket.com`, `somename.jira.whatever`, …)? Could you tell me the domains used for Jira & Confluence?
Since the issue is obviously specific to some Atlassian products I'd err on not adding the general rule you proposed above.

**Comment by fishman** [comment] 2018-09-16 02:28
here is a more granular version:

id.atlassian.com > *.atlassian.net
id.atlassian.com > *.atl-paas.net

**Comment by fishman** [comment] 2018-09-17 17:50
i'm wrong:

1. this doesn't fully work as expected
2. bitbucket is an identity provider and bitbucket does it's auth through id.atlassian.com

so if you don't do what pera suggested it won't work

**Comment by alexander255** [comment] 2018-09-23 10:56
@pera: Thank you for working on this! If you haven't seen it already, [the wiki arcticle](https://github.com/meh/smart-referer/wiki/Gathering-Data-for-Whitelist-Entries) may be of help.

Also, if you have the time could you check whether these Atlassian services are also broken when changing **Rewrite Mode** from **Use the URL you're going to** to **Send nothing, looking like a direct hit** in extension settings? I'm currently investigating making this the default mode (#113) and your feedback would be very valuable here!

**Comment by pera** [comment] 2018-09-24 20:01
@alexander255 glad to be of help :) so I could finally find the rule: `id.atlassian.com>atlassian.net`
I guess the problem when I first tried atlassian.net was that I actually tried `*.atlassian.net` instead of just `atlassian.net`.

About the Rewrite Mode: it doesn't seem to have any effect on Jira (tried both modes with and without the exception rule).

**Comment by alexander255** [comment] 2018-09-27 10:04
Sorry for the delay, I've pushed the whitelist change now.
Pro tip regarding the `*.<domain>` issue: If you prepend just a dot in front of the domain name it will match both the base domain as well as all subdomains (`.atlassian.net` in this case). :wink: 

Please test to make sure it works as expected:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list
 4. Make sure the **Use default whitelist** option is checked under **Whitelist Sources**
 5. Remove any custom **Exception** rules that may be related to this issue
 6. Click on the **Disable** button towards to bottom of *Smart Referer*'s extension page
 7. Wait for *Smart Referer* to be disabled then click the **Enable** to re-enable button (this will force a whitelist update)
 8. Check if your page is working now 🙂 

Feel free to close this issue if it works now!

**Closed** 2018-09-29 01:53 UTC
Labels: Whitelist
